
CXXFLAGS = -std=c++14 -g -Wall -O1

OBJ = main.o game.o board.o cluster.o square.o tools.o Canvas.o GridChar.o MixedChar.o Viewer.o

TARGETS = SudokuHelper

.PHONY: all clean
all: $(TARGETS)

SudokuHelper: $(OBJ)
	$(CXX)  -o $@ $(CXXFLAGS) $(OBJ)

clean:
	rm -f $(OBJ) $(TARGETS)

main.o: main.cpp
game.o: game.cpp game.hpp frame.hpp stack.hpp exception.hpp
board.o: board.cpp board.hpp CanView.hpp
cluster.o: cluster.cpp cluster.hpp
square.o: square.cpp square.hpp
tools.o: tools.cpp tools.hpp
Canvas.o: Canvas.cpp Canvas.hpp
GridChar.o: GridChar.cpp GridChar.hpp
MixedChar.o: MixedChar.cpp MixedChar.hpp
Viewer.o: Viewer.cpp Viewer.hpp
